@echo off
setlocal enabledelayedexpansion
title SVFI Pipeline Configurator

set "CARPETA=%~dp0"
set "CARPETA=%CARPETA:~0,-1%"

cls
echo ============================================
echo   SVFI Pipeline Configurator
echo ============================================
echo.
echo   Project folder: %CARPETA%
echo.

REM ---------- pythonw ----------
set "PYTHONW="
for /f "delims=" %%P in ('where pythonw 2^>nul') do (
    if not defined PYTHONW set "PYTHONW=%%P"
)
if not defined PYTHONW (
    if exist "C:\Users\%USERNAME%\AppData\Local\Python\bin\pythonw.exe" (
        set "PYTHONW=C:\Users\%USERNAME%\AppData\Local\Python\bin\pythonw.exe"
    )
)

echo [1/3] pythonw.exe path
if defined PYTHONW (
    echo       Detected: !PYTHONW!
    set /p "IN_PY=      Press Enter to use ^| or type another path: "
    if not "!IN_PY!"=="" set "PYTHONW=!IN_PY!"
) else (
    set /p "PYTHONW=      Enter the full path: "
)

if not defined PYTHONW (
    echo   ERROR: pythonw.exe is required.
    pause
    exit /B 1
)

REM ---------- SVFI ----------
set "SVFI_DEFAULT=D:\SteamLibrary\steamapps\common\SVFI\one_line_shot_args.exe"
echo.
echo [2/3] SVFI path ^(one_line_shot_args.exe^)
if exist "!SVFI_DEFAULT!" (
    echo       Detected: !SVFI_DEFAULT!
    set /p "IN_SVFI=      Press Enter to use ^| or type another path: "
    if "!IN_SVFI!"=="" (set "SVFI=!SVFI_DEFAULT!") else (set "SVFI=!IN_SVFI!")
) else (
    set /p "SVFI=      Enter the full path: "
)

REM ---------- Preset ----------
set "PRESET_DEFAULT=!CARPETA!\mi_preset_svfi.ini"
echo.
echo [3/3] Preset .ini path
echo       Suggested: !PRESET_DEFAULT!
set /p "IN_PRESET=      Press Enter to use ^| or type another path: "
if "!IN_PRESET!"=="" (set "PRESET=!PRESET_DEFAULT!") else (set "PRESET=!IN_PRESET!")

echo.
echo ============================================
echo   Updating files...
echo ============================================
echo.

REM ---------- Write config.txt ----------
(
    echo # SVFI Pipeline Configuration
    echo # Automatically generated by Config.bat
    echo.
    echo SVFI_PATH=!SVFI!
    echo PRESET_PATH=!PRESET!
) > "!CARPETA!\config.txt"
echo   [OK] config.txt

REM ---------- Regenerate lanzar_svfi.vbs ----------
set "VBS=!CARPETA!\lanzar_svfi.vbs"
(
    echo Set fso = CreateObject^("Scripting.FileSystemObject"^)
    echo Set shell = CreateObject^("WScript.Shell"^)
    echo.
    echo strScriptDir = fso.GetParentFolderName^(WScript.ScriptFullName^)
    echo strCarpetaFile = strScriptDir ^& "\carpeta_actual.txt"
    echo.
    echo If Not fso.FileExists^(strCarpetaFile^) Then
    echo     WScript.Quit 1
    echo End If
    echo.
    echo Set f = fso.OpenTextFile^(strCarpetaFile, 1^)
    echo carpeta = f.ReadAll
    echo f.Close
    echo carpeta = Trim^(carpeta^)
    echo.
    echo strPython = "!PYTHONW!"
    echo strScript = strScriptDir ^& "\svfi_orquestador.py"
    echo.
    echo comando = """" ^& strPython ^& """ """ ^& strScript ^& """ """ ^& carpeta ^& """"
    echo shell.Run comando, 0, False
) > "!VBS!"
echo   [OK] lanzar_svfi.vbs

echo.
echo ============================================
echo   Configuration completed
echo ============================================
echo.
echo   pythonw:  !PYTHONW!
echo   SVFI:     !SVFI!
echo   Preset:   !PRESET!
echo   Folder:   !CARPETA!
echo.
pause
exit /B 0